steps:
  # Step 1: Install tools
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'setup_tools'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "--- [setup] Installing psql & Cloud SQL Proxy ---"
        apt-get update && apt-get install -y postgresql-client curl
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.10.0/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy
        ./cloud-sql-proxy --version

  # Step 2: Validate database content
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'validate_records'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail

        echo "--- [validate] Reading DB connection name ---"
        DB_CONNECTION_NAME=$(cat ./infra/terraform/db_conn_name.txt)
        echo "Using connection: $DB_CONNECTION_NAME"

        echo "--- [validate] Starting Cloud SQL Proxy ---"
        ./cloud-sql-proxy --private-ip "$DB_CONNECTION_NAME" &
        PROXY_PID=$!
        sleep 5

        echo "--- [validate] Checking proxy readiness ---"
        if ! pg_isready -h 127.0.0.1 -U "${_SQL_USER}" -d "${_SQL_DBNAME}" -t 5; then
          echo "Proxy not ready. Exiting."
          kill $PROXY_PID 2>/dev/null || true
          exit 1
        fi

        echo "--- [validate] Running validation query ---"
        COUNT=$(PGPASSWORD="$PGPASSWORD" psql --host=127.0.0.1 --username="${_SQL_USER}" --dbname="${_SQL_DBNAME}" -t -c "SELECT COUNT(*) FROM connections;" | xargs)
        echo "Found $COUNT records in connections table."

        kill $PROXY_PID
        if (( COUNT > 0 )); then
          echo "--- [validate] ✅ Validation successful ---"
          exit 0
        else
          echo "--- [validate] ❌ No records found ---"
          exit 1
        fi

    secretEnv: ['PGPASSWORD']

# Cloud Build substitutions
substitutions:
  _SQL_REGION: 'asia-south1'
  _SQL_INSTANCE_NAME: 'netprobe-db'
  _SQL_USER: 'netprobe_user'
  _SQL_DBNAME: 'netprobe_logs'

# Secrets
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/db-password/versions/latest
      env: 'PGPASSWORD'

timeout: '300s'
