steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'setup_tools'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "--- Installing psql & Downloading Proxy ---"
        apt-get update && apt-get install -y postgresql-client curl
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.10.0/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy
        ./cloud-sql-proxy --version

  # Step 2: Start Proxy & Apply Schema
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'apply_schema'
    env:
      - 'SQL_REGION=${_SQL_REGION}'
      - 'SQL_INSTANCE_NAME=${_SQL_INSTANCE_NAME}'
      - 'SQL_USER=${_SQL_USER}'
      - 'SQL_DBNAME=${_SQL_DBNAME}'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        DB_CONNECTION_NAME="projects/${PROJECT_ID}/locations/${SQL_REGION}/instances/${SQL_INSTANCE_NAME}"
        echo "--- Starting Cloud SQL Proxy ---"
        ./cloud-sql-proxy --private-ip $DB_CONNECTION_NAME &
        PROXY_PID=$!
        sleep 5

        echo "Waiting for proxy (PID $PROXY_PID) to accept connections on localhost..."
        for i in {1..10}; do
          if pg_isready -h 127.0.0.1 -U $SQL_USER -d $SQL_DBNAME; then echo "Proxy ready."; break; fi
          if ! ps -p $PROXY_PID > /dev/null; then echo "Proxy died!"; exit 1; fi
          echo "Attempt $i/10 failed. Waiting 15s..."; sleep 15
        done
        if ! pg_isready -h 127.0.0.1 -U $SQL_USER -d $SQL_DBNAME; then echo "Proxy timed out."; kill $PROXY_PID 2>/dev/null || true; exit 1; fi
        echo "--- Applying schema via proxy ---"
        psql --host=127.0.0.1 --username=$SQL_USER --dbname=$SQL_DBNAME <<-EOF
          CREATE TABLE connections (
              id SERIAL PRIMARY KEY, ts TIMESTAMP WITH TIME ZONE NOT NULL, uid VARCHAR(255) UNIQUE NOT NULL,
              source_ip INET NOT NULL, source_port INTEGER NOT NULL, destination_ip INET NOT NULL,
              destination_port INTEGER NOT NULL, proto VARCHAR(6), service VARCHAR(255), duration FLOAT,
              orig_bytes BIGINT, resp_bytes BIGINT, conn_state VARCHAR(10),
              logged_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
          );
        EOF
        echo "--- Schema applied successfully ---"
        kill $PROXY_PID
    secretEnv: ['PGPASSWORD']

    substitutions:
      _SQL_REGION: 'asia-south1'
      _SQL_INSTANCE_NAME: 'netprobe-db'
      _SQL_USER: 'netprobe_user'
      _SQL_DBNAME: 'netprobe_logs'

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/db-password/versions/latest
    env: 'PGPASSWORD'

timeout: '600s'