steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "--- Installing psql & Downloading Proxy ---"
        apt-get update && apt-get install -y postgresql-client curl
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.10.0/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy
        ./cloud-sql-proxy --version # Verify

  # Step 2: Start Proxy & Validate Records
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "--- Starting Cloud SQL Proxy ---"
        ./cloud-sql-proxy --private-ip projects/${PROJECT_ID}/locations/${_SQL_REGION}/instances/${_SQL_INSTANCE_NAME} &
        PROXY_PID=$!
        sleep 5

        echo "Waiting for proxy (PID $PROXY_PID) to accept connections on localhost..."
        if ! pg_isready -h 127.0.0.1 -U ${_SQL_USER} -d ${_SQL_DBNAME} -t 5; then
           echo "Proxy did not become ready quickly."; kill $PROXY_PID 2>/dev/null || true; exit 1;
        fi

        echo "--- Querying database via proxy ---"
        RESULT=$(psql --host=127.0.0.1 --username=${_SQL_USER} --dbname=${_SQL_DBNAME} -t -c "SELECT COUNT(*) FROM connections;")
        COUNT=$(echo $RESULT | xargs)

        echo "Found $COUNT records."
        kill $PROXY_PID # Stop proxy
        if (( COUNT > 0 )); then echo "Validation successful."; exit 0;
        else echo "Validation failed."; exit 1; fi
    secretEnv: ['PGPASSWORD']
    substitutions:
      _SQL_REGION: 'asia-south1'
      _SQL_INSTANCE_NAME: 'netprobe-db'
      _SQL_USER: 'netprobe_user'
      _SQL_DBNAME: 'netprobe_logs'

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/db-password/versions/latest
    env: 'PGPASSWORD'

timeout: '300s'