steps:
  # 1. Setup & Schema Apply (Combined)
  # We use our pre-baked image, so no installation steps needed!
  - name: 'asia-south1-docker.pkg.dev/$PROJECT_ID/netprobe-docker-repo/schema-tool:latest'
    id: 'apply_schema'
    secretEnv: ['PGPASSWORD']
    entrypoint: 'bash'
    args:
        - '-c'
        - |
          set -e
          echo "--- [Optimized] Starting Cloud SQL Proxy ---"
          # The proxy is already in /usr/local/bin/
          cloud-sql-proxy --private-ip "${PROJECT_ID}:${_SQL_REGION}:${_SQL_INSTANCE_NAME}" &
          
          echo "Waiting for proxy..."
          sleep 2 # Much shorter sleep needed now
          
          # We loop briefly to ensure connection before running psql
          # (We can assume pg_isready is available if we installed postgresql-client)
          until pg_isready -h 127.0.0.1 -U "${_SQL_USER}" -d "${_SQL_DBNAME}"; do
            echo "Waiting for DB..."
            sleep 1
          done

          echo "--- Applying Schema ---"
          # Source code is automatically mounted by Cloud Build
          psql --host=127.0.0.1 --username="${_SQL_USER}" --dbname="${_SQL_DBNAME}" -f infra/db_init/1_schema.sql
          
          echo "--- Schema applied successfully ---"
          pkill -f cloud-sql-proxy || true

substitutions:
  _SQL_REGION: 'asia-south1'
  _SQL_INSTANCE_NAME: 'netprobe-db'
  _SQL_USER: 'netprobe_user'
  _SQL_DBNAME: 'netprobe_logs'

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/db-password/versions/latest
    env: 'PGPASSWORD'

timeout: '600s'

options:
  pool:
    name: 'projects/${PROJECT_ID}/locations/asia-south1/workerPools/netprobe-private-pool'