steps:
  # Step 1: Install psql
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "--- Installing psql ---"
        apt-get update && apt-get install -y postgresql-client

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "--- [validate] Connecting via gcloud and querying database ---"
        COUNT=$(gcloud alpha sql connect netprobe-db --user=netprobe_user --private-ip --quiet -- <<EOF | xargs
          SELECT COUNT(*) FROM connections;
        EOF
        )

        echo "Found $COUNT records in the connections table."
        if (( COUNT > 0 )); then
          echo "Validation successful."
          exit 0
        else
          echo "Validation failed: No records found."
          exit 1
        fi
    secretEnv: ['PGPASSWORD']

availableSecrets:
  secretManager:
  - versionName: projects/netprobe-473119/secrets/db-password/versions/latest
    env: 'PGPASSWORD'

timeout: '300s'