steps:
  # Validate Records using pre-baked image
  - name: 'asia-south1-docker.pkg.dev/$PROJECT_ID/netprobe-docker-repo/schema-tool:latest'
    id: 'validate_records'
    secretEnv: ['PGPASSWORD']
    entrypoint: 'bash'
    args:
        - '-c'
        - |
          set -e
          echo "--- [Optimized] Starting Cloud SQL Proxy ---"
          cloud-sql-proxy --private-ip "${PROJECT_ID}:${_SQL_REGION}:${_SQL_INSTANCE_NAME}" &
          
          echo "Waiting for proxy..."
          until pg_isready -h 127.0.0.1 -U "${_SQL_USER}" -d "${_SQL_DBNAME}"; do
            sleep 1
          done

          echo "--- Checking for records ---"
          if psql --host=127.0.0.1 --username="${_SQL_USER}" --dbname="${_SQL_DBNAME}" -t -c "SELECT 1 FROM connections LIMIT 1;" | grep -q 1; then
            echo "Validation successful: Records found."
          else
            echo "Validation failed: No records found."
            pkill -f cloud-sql-proxy || true
            exit 1
          fi
          
          pkill -f cloud-sql-proxy || true

substitutions:
  _SQL_REGION: 'asia-south1'
  _SQL_INSTANCE_NAME: 'netprobe-db'
  _SQL_USER: 'netprobe_user'
  _SQL_DBNAME: 'netprobe_logs'

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/db-password/versions/latest
    env: 'PGPASSWORD'

timeout: '300s'

options:
  pool:
    name: 'projects/${PROJECT_ID}/locations/asia-south1/workerPools/netprobe-private-pool'