steps:
  # Step 1: Install tools (No changes)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'setup_tools'
    entrypoint: 'bash'
    args: ['-c', 'set -e; echo "--- [validate] Installing tools ---"; apt-get update && apt-get install -y postgresql-client curl; curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.10.0/cloud-sql-proxy.linux.amd64; chmod +x cloud-sql-proxy; ./cloud-sql-proxy --version']

  # Step 2: Start Proxy & Validate Records
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'validate_records'
    secretEnv: ['PGPASSWORD']
    entrypoint: 'bash'
    args:
        - '-c'
        - |
          set -e
          echo "Using provided PGPASSWORD (masked): [$$PGPASSWORD]"
          echo "--- [validate] Starting Cloud SQL Proxy ---"
          ./cloud-sql-proxy --private-ip "${PROJECT_ID}:${_SQL_REGION}:${_SQL_INSTANCE_NAME}" &
          sleep 5

          echo "Waiting for proxy..."
          apt-get update && apt-get install -y postgresql-client
          if psql --host=127.0.0.1 --username="${_SQL_USER}" --dbname="${_SQL_DBNAME}" -t -c "SELECT 1 FROM connections LIMIT 1;" | grep -q 1; then
            echo "Validation successful: Records found."
          else
            echo "Validation failed: No records found."
            echo "--- [validate] Shutting down proxy ---"
            pkill -f cloud-sql-proxy || echo "Proxy already stopped."
            exit 1
          fi
          echo "--- [validate] Shutting down proxy ---"
          pkill -f cloud-sql-proxy || echo "Proxy already stopped."

substitutions:
  _SQL_REGION: 'asia-south1'
  _SQL_INSTANCE_NAME: 'netprobe-db'
  _SQL_USER: 'netprobe_user'
  _SQL_DBNAME: 'netprobe_logs'

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/db-password/versions/latest
    env: 'PGPASSWORD'

timeout: '300s'

options:
  pool:
    name: 'projects/${PROJECT_ID}/locations/asia-south1/workerPools/netprobe-private-pool'