steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "--- Installing psql ---"
        apt-get update && apt-get install -y postgresql-client

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "--- [validate] Connecting via gcloud and querying database ---"
        gcloud alpha sql connect netprobe-db --user=netprobe_user --private-ip --quiet -- \
          psql -qtAX --dbname=netprobe_logs -c "SELECT COUNT(*) FROM connections WHERE COUNT(*) > 0;" \
          || (echo 'Validation failed: No records found.' && exit 1)

        echo "Validation successful: Records found in the database."
    secretEnv: ['PGPASSWORD']

availableSecrets:
  secretManager:
  - versionName: projects/netprobe-473119/secrets/db-password/versions/latest
    env: 'PGPASSWORD'

timeout: '300s'