steps:
  # Step 1: Install tools
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'setup_tools'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "--- [setup] Installing psql & Cloud SQL Proxy ---"
        apt-get update && apt-get install -y postgresql-client curl
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.10.0/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy
        ./cloud-sql-proxy --version

  # Step 2: Start Proxy & Apply Schema
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'apply_schema'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail

        echo "--- [schema] Reading DB connection name ---"
        DB_CONNECTION_NAME=$(cat ./infra/terraform/db_conn_name.txt)
        echo "Using connection: $DB_CONNECTION_NAME"

        echo "--- [schema] Starting Cloud SQL Proxy ---"
        ./cloud-sql-proxy --private-ip "$DB_CONNECTION_NAME" &
        PROXY_PID=$!
        sleep 5

        echo "--- [schema] Waiting for proxy to accept connections ---"
        for i in {1..10}; do
          if pg_isready -h 127.0.0.1 -U "${_SQL_USER}" -d "${_SQL_DBNAME}"; then
            echo "Proxy is ready."
            break
          fi
          if ! ps -p $PROXY_PID > /dev/null; then
            echo "Proxy process died unexpectedly."
            exit 1
          fi
          echo "Attempt $i/10 failed, waiting..."
          sleep 10
        done

        echo "--- [schema] Applying database schema ---"
        PGPASSWORD="$PGPASSWORD" psql --host=127.0.0.1 --username="${_SQL_USER}" --dbname="${_SQL_DBNAME}" <<'EOF'
          CREATE TABLE IF NOT EXISTS connections (
            id SERIAL PRIMARY KEY,
            src_ip VARCHAR(50),
            dest_ip VARCHAR(50),
            timestamp TIMESTAMP DEFAULT NOW()
          );
        EOF

        echo "--- [schema] Schema applied successfully ---"
        kill $PROXY_PID

    secretEnv: ['PGPASSWORD']

# Cloud Build substitutions
substitutions:
  _SQL_REGION: 'asia-south1'
  _SQL_INSTANCE_NAME: 'netprobe-db'
  _SQL_USER: 'netprobe_user'
  _SQL_DBNAME: 'netprobe_logs'

# Secrets
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/db-password/versions/latest
      env: 'PGPASSWORD'

timeout: '600s'
