steps:
  # Step 1: Install psql client & Download Proxy
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'setup_tools'
    entrypoint: 'bash'
    args: ['-c', 'set -e; echo "--- Installing tools ---"; apt-get update && apt-get install -y postgresql-client curl; curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.10.0/cloud-sql-proxy.linux.amd64; chmod +x cloud-sql-proxy; ./cloud-sql-proxy --version']

  # Step 2: Start Proxy & Validate Records
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'validate_records'
    entrypoint: 'bash'
    args:
        - '-c'
        - |
          set -e
          echo "--- Starting Cloud SQL Proxy for ${_DB_CONNECTION_NAME} ---"
          # Use the _DB_CONNECTION_NAME substitution DIRECTLY in the command
          ./cloud-sql-proxy --private-ip "${_DB_CONNECTION_NAME}" &
          sleep 5 # Give proxy time to start (no PID capture needed)

          echo "Waiting for proxy..."
          if ! pg_isready -h 127.0.0.1 -U "${_SQL_USER}" -d "${_SQL_DBNAME}" -t 15; then
             echo "Proxy did not become ready quickly."
             pkill -f cloud-sql-proxy || true # Kill by name
             exit 1
          fi

          echo "--- Querying database ---"
          RESULT=$(psql --host=127.0.0.1 --username="${_SQL_USER}" --dbname="${_SQL_DBNAME}" -t -c "SELECT COUNT(*) FROM connections;")
          COUNT=$(echo $RESULT | xargs)

          echo "Found $COUNT records."
          echo "--- Shutting down proxy ---"
          pkill -f cloud-sql-proxy || echo "Proxy already stopped."

          if (( COUNT > 0 )); then echo "Validation successful."; exit 0;
          else echo "Validation failed."; exit 1; fi

substitutions:
  _SQL_REGION: 'asia-south1'
  _SQL_INSTANCE_NAME: 'netprobe-db'
  _SQL_USER: 'netprobe_user'
  _SQL_DBNAME: 'netprobe_logs'
  _DB_CONNECTION_NAME: ''
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/db-password/versions/latest
    env: 'PGPASSWORD'

timeout: '300s'