steps:
  # Step 1: Install tools (No changes needed here)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'setup_tools'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "--- Installing psql & Downloading Proxy ---"
        apt-get update && apt-get install -y postgresql-client curl
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.10.0/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy
        ./cloud-sql-proxy --version

  # Step 2: Start Proxy & Apply Schema (Uses substitutions directly)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'apply_schema'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        # Construct connection name using substitutions directly
        DB_CONNECTION_NAME=$(cat ./infra/terraform/db_conn_name.txt)

        echo "--- Starting Cloud SQL Proxy for $DB_CONNECTION_NAME ---"
        ./cloud-sql-proxy --private-ip "$DB_CONNECTION_NAME" &
        PROXY_PID=$!
        sleep 5

        echo "Waiting for proxy (PID $PROXY_PID) to accept connections on localhost..."
        for i in {1..10}; do
          # Use substitutions directly for user and dbname
          if pg_isready -h 127.0.0.1 -U "${_SQL_USER}" -d "${_SQL_DBNAME}"; then echo "✅ Proxy ready."; break; fi
          if ! ps -p $PROXY_PID > /dev/null; then echo "❌ Proxy died!"; exit 1; fi
          echo "Attempt $i/10 failed. Waiting 15s..."; sleep 15
        done
        if ! pg_isready -h 127.0.0.1 -U "${_SQL_USER}" -d "${_SQL_DBNAME}"; then echo "❌ Proxy timed out."; kill $PROXY_PID 2>/dev/null || true; exit 1; fi

        echo "--- Applying schema via proxy ---"
        # Use substitutions directly for user and dbname
        psql --host=127.0.0.1 --username="${_SQL_USER}" --dbname="${_SQL_DBNAME}" <<-EOF
          CREATE TABLE connections (...); # Truncated for brevity
        EOF
        echo "--- Schema applied successfully ---"
        kill $PROXY_PID
    secretEnv: ['PGPASSWORD']

# Define substitutions (Remain the same)
substitutions:
  _SQL_REGION: 'asia-south1'
  _SQL_INSTANCE_NAME: 'netprobe-db'
  _SQL_USER: 'netprobe_user'
  _SQL_DBNAME: 'netprobe_logs'

# Make secret available (Remains the same)
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/db-password/versions/latest
    env: 'PGPASSWORD'

timeout: '600s'